
SELECT count(*) FROM commiss_pr


SELECT * FROM table19 t
RIGHT OUTER JOIN MAP_TABLE19 mt ON t.nstatus_pre = mt.NSTATUS_PRE 
ORDER BY 1


SELECT * FROM map_table19


SELECT * FROM table19
WHERE sstatregt=1


SELECT * FROM INTERM_TYP it 


SELECT * FROM tr_report
WHERE sresult = 'KO'



------------------------------------
---DETAIL_PRE-----------------------
-----------------------------------


--en detail_pre
--NO pueden ser nulos: nbranch,nproduct,ncertype,nreceipt,ndigit,npaynumbe,nid_bill,stype_detai,nbranch_est,nbranch_led
--pk: SCERTYPE, NBRANCH, NPRODUCT, NRECEIPT, NDIGIT, NPAYNUMBE, NID_BILL

--NBRANCH_EST --> TABLE71
--NBRANCH_LED --> TABLE75

SELECT * FROM table71 --> 99 NO tiene // Ponemos esto por ahora? (NBRANCH_EST)

SELECT * FROM table75 --> 99 NO tiene // Ponemos Esto por ahora?


SELECT SCERTYPE, NBRANCH, NPRODUCT, NRECEIPT, NDIGIT, NPAYNUMBE, NID_BILL,count(*)
FROM detail_pre
GROUP by SCERTYPE, NBRANCH, NPRODUCT, NRECEIPT, NDIGIT, NPAYNUMBE, NID_BILL
HAVING count(*)>1


DELETE FROM INTERMEDIO.DETAIL_PRE

INSERT INTO INTERMEDIO.DETAIL_PRE
(NPRODUCT, NRECEIPT, NBRANCH, SCERTYPE, NDIGIT, NPAYNUMBE, NID_BILL, SADDSUINI, STYPE_DETAI, NDET_CODE, DCOMPDATE, NCAPITAL, NCOMMI_RATE, NCOMMISION, NPREMIUM, NTAX, NBILL_ITEM, NBRANCH_EST, NBRANCH_LED,
NBRANCH_REI, NUSERCODE, NPREMANUAL, SADDTAX, NCOMANUAL, NPREMIUMA, NPREMIUME, NTAXAMOUNT, NRECAMOUNT, NDESCAMOUNT, NREL_IDBILL, SCLIENT, NDISSUR_TYPE, NPROVINCE, NVAT_SITUATION, SBATCHGENERATION,
DBATCHGENERATION, NTAXRATE)

SELECT
	INTERMEDIO.MAP_PRODUCTS.NPRODUCT AS NPRODUCT,
	TRIM(INTERMEDIO.SEFMRECI.RECIBANN) || TRIM(INTERMEDIO.SEFMRECI.RECIBTIP) || TRIM(INTERMEDIO.SEFMRECI.RECIBSEC) AS NRECEIPT,
	INTERMEDIO.MAP_PRODUCTS.NBRANCH AS NBRANCH,
	2 AS SCERTYPE,
	0 AS NDIGIT,
	0 AS NPAYNUMBE,
	ROW_NUMBER() OVER (PARTITION BY TRIM(INTERMEDIO.SEFMRECI.RECIBANN) || TRIM(INTERMEDIO.SEFMRECI.RECIBTIP) || TRIM(INTERMEDIO.SEFMRECI.RECIBSEC)  ORDER BY INTERMEDIO.SEFMRECI.RECIBANN,INTERMEDIO.SEFMRECI.RECIBTIP,INTERMEDIO.SEFMRECI.RECIBSEC) AS NID,
--NULL AS NID_BILL, --Lo genera el sistema de VT
	NULL AS SADDSUINI, --tomar desde la tabla del producto
	/*
	 	STYPE_DETAI
	 	1 - cobetura 2- componente recibo (ver valores codigos) analizar ejemplo de Gilmer, Ver detalle según definicion de NORA
		En VT los valores son:
		1 - Coberturas
		2 o 5 - Recargos
		3 - Impuestos
		4 o 6 - Descuentos 
	*/
	NULL AS STYPE_DETAI,
	/*
		NDET_CODE
		Detalle del movimiento (cobertura o componente del recibo) (Es el código de cobertura de la tabla la tabla COVER) Código de cobertura, si STYPE_DETAI es 1
		o de recargos y descuentos (3, 5, 6 en la Discx_prem) Definido en el producto
	*/
	NULL AS NDET_CODE,
	SYSDATE AS DCOMPDATE,
	NULL AS NCAPITAL, --(/100) SEFMECON.CAPITASEG (COBERCOD 100 si no tiene 100 entonces buscar 200)
	0 AS NCOMMI_RATE,
	0 AS NCOMMISION,
	(INTERMEDIO.SEFMRECI.PRIMAIMP / 100) AS NPREMIUM, --SEFMRECI.PRIMAIMP (acá completar el importe del descuento, boonificacion, derecho emision, sellados, etc.)
	0 AS NTAX,
	NULL AS NBILL_ITEM,
	NULL AS NBRANCH_EST, --tabla de productos (TABLE71) (en DB 28 - Sepelio colectivo)
	NULL AS NBRANCH_LED, --tabla de productos (TABLE75) (en DB 28 - Sepelio colectivo)
	NULL AS NBRANCH_REI, --tabla de productos (TABLE5000) (en DB 99 - No tiene)
	-1 AS NUSERCODE,
	NULL AS NPREMANUAL, --PRIMAIMP * COBROFOR OF SEFMPOLI
	NULL AS SADDTAX, --tabla de productos
	NULL AS NCOMANUAL, --comision de esa cobertura para todos los intemediarios.
	(INTERMEDIO.SEFMRECI.PRIMAIMP / 100) AS NPREMIUMA, --Lo mismo que NPREMIUM
	0 AS NPREMIUME,
	0 AS NTAXAMOUNT,
	0 AS NRECAMOUNT,
	0 AS NDESCAMOUNT,
	0 AS NREL_IDBILL,
	MC.SCLIENT AS SCLIENT,
	NULL AS NDISSUR_TYPE, --tomar desde la tabla del producto (TABLE3007) (en DB null o 6 - Tasa de Superintendencia (SSN))
	INTERMEDIO.MAP_PROVINCE.NPROVINCE AS NPROVINCE,
	NULL AS NVAT_SITUATION,
	NULL AS SBATCHGENERATION,
	NULL AS DBATCHGENERATION,
	NULL AS NTAXRATE
FROM INTERMEDIO.SEFMPOLI
INNER JOIN INTERMEDIO.MAP_PRODUCTS ON --Verificar LEFT
	INTERMEDIO.MAP_PRODUCTS.RAMOPCOD = INTERMEDIO.SEFMPOLI.RAMOPCOD AND
	INTERMEDIO.SEFMPOLI.SWCLIENT = NVL(INTERMEDIO.MAP_PRODUCTS.SWCLIENT, ' ')
LEFT JOIN INTERMEDIO.SEFMPECO ON
	INTERMEDIO.SEFMPECO.CIAASCOD = INTERMEDIO.SEFMPOLI.CIAASCOD AND
	INTERMEDIO.SEFMPECO.RAMOPCOD = INTERMEDIO.SEFMPOLI.RAMOPCOD AND
	INTERMEDIO.SEFMPECO.POLIZANN = INTERMEDIO.SEFMPOLI.POLIZANN AND
	INTERMEDIO.SEFMPECO.POLIZSEC = INTERMEDIO.SEFMPOLI.POLIZSEC AND
	INTERMEDIO.SEFMPECO.SUPLENUM = INTERMEDIO.SEFMPOLI.SUPLENUM AND
	(TRIM(INTERMEDIO.SEFMPECO.ASEGUTIP) IS NULL OR TRIM(INTERMEDIO.SEFMPECO.ASEGUTIP) = 'C')
LEFT JOIN (
	SELECT
		INTERMEDIO.MAP_CLIENT.CLIENSEC,
		INTERMEDIO.MAP_CLIENT.SCLIENT,
		INTERMEDIO.MAP_CLIENT.APELLIDO,
		INTERMEDIO.MAP_CLIENT.NOMBRE,
		INTERMEDIO.MAP_CLIENT.DOCUMENTO,
		INTERMEDIO.MAP_CLIENT.NTYPCLIENTDOC,
		INTERMEDIO.MAP_CLIENT.NPERSON_TYP
	FROM INTERMEDIO.MAP_CLIENT
	GROUP BY
		INTERMEDIO.MAP_CLIENT.CLIENSEC,
		INTERMEDIO.MAP_CLIENT.SCLIENT,
		INTERMEDIO.MAP_CLIENT.APELLIDO,
		INTERMEDIO.MAP_CLIENT.NOMBRE,
		INTERMEDIO.MAP_CLIENT.DOCUMENTO,
		INTERMEDIO.MAP_CLIENT.NTYPCLIENTDOC,
		INTERMEDIO.MAP_CLIENT.NPERSON_TYP
) MC ON MC.CLIENSEC = INTERMEDIO.SEFMPECO.CLIENSEC 
INNER JOIN INTERMEDIO.SEFMRECI ON
	INTERMEDIO.SEFMRECI.CIAASCOD = INTERMEDIO.SEFMPOLI.CIAASCOD AND
	INTERMEDIO.SEFMRECI.RAMOPCOD = INTERMEDIO.SEFMPOLI.RAMOPCOD AND
	INTERMEDIO.SEFMRECI.POLIZANN = INTERMEDIO.SEFMPOLI.POLIZANN AND
	INTERMEDIO.SEFMRECI.POLIZSEC = INTERMEDIO.SEFMPOLI.POLIZSEC AND
	INTERMEDIO.SEFMRECI.SUPLENUM = INTERMEDIO.SEFMPOLI.SUPLENUM
LEFT JOIN INTERMEDIO.SEFMDOMI ON
	INTERMEDIO.SEFMDOMI.CLIENSEC = MC.CLIENSEC 
LEFT JOIN INTERMEDIO.MAP_PROVINCE ON
	LPAD(TO_CHAR(INTERMEDIO.MAP_PROVINCE.PAISSCOD), 2, '0') = INTERMEDIO.SEFMDOMI.PAISSCOD AND
	INTERMEDIO.MAP_PROVINCE.PROVICOD = INTERMEDIO.SEFMDOMI.PROVICOD
WHERE
--ROWNUM <= 100 AND
INTERMEDIO.SEFMPOLI.POLIZANN >= 0 AND
INTERMEDIO.SEFMPOLI.POLIZSEC > 0 AND
--TRIM(INTERMEDIO.SEFMPOLI.SITUCPOL) IS NULL AND
TRIM(INTERMEDIO.SEFMRECI.RECIBANN) || TRIM(INTERMEDIO.SEFMRECI.RECIBTIP) || TRIM(INTERMEDIO.SEFMRECI.RECIBSEC) IN (102348910,102365003,102956178,152649209) 
AND INTERMEDIO.SEFMPOLI.SUPLENUM = (
	SELECT MAX(SUPLENUM)
	FROM INTERMEDIO.SEFMPOLI MAYOR
	WHERE
	INTERMEDIO.SEFMPOLI.CIAASCOD = MAYOR.CIAASCOD AND
	INTERMEDIO.SEFMPOLI.RAMOPCOD = MAYOR.RAMOPCOD AND
	INTERMEDIO.SEFMPOLI.POLIZANN = MAYOR.POLIZANN AND
	INTERMEDIO.SEFMPOLI.POLIZSEC = MAYOR.POLIZSEC AND
	INTERMEDIO.SEFMPOLI.CERTIPOL = MAYOR.CERTIPOL AND
	INTERMEDIO.SEFMPOLI.CERTIANN = MAYOR.CERTIANN AND
	INTERMEDIO.SEFMPOLI.CERTISEC = MAYOR.CERTISEC
)
